# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f4339c56d020307eac5ffcdae5f0c97538311bd1810160439e21df28fa87b1f99629f286a1504e6a091bea61ef62ad5799a48717c6244845abcca9ae24e915c

test:
  secret_key_base: f29435fda8cc448b36d40d7299bf63dd1382d7ac347332fbcf0240491cc5d892b42a15cc752ba43c6d78cdefc231ef1bb5d411a9f69ea2eeb0ff5c3923b400c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
